CONTRIBUTING.md
README.md
RELEASE.md

/kind documentation
update docs to explain what it is briefly
Fixes #3 
No.

update(docs): update readme to explain what it is briefly

---

example/main.go
guest/api/status.go
guest/api/types.go
guest/filter.go
guest/internal/imports/host.go
guest/internal/imports/imports.go
guest/internal/imports/imports_stub.go
guest/internal/imports/mem.go
kubernetes/proto/tools/tools.go
scheduler/cmd/scheduler/main.go
scheduler/pkg/plugins/wasm/config.go
scheduler/pkg/plugins/wasm/guest.go
scheduler/pkg/plugins/wasm/host.go
scheduler/pkg/plugins/wasm/mem.go
scheduler/pkg/plugins/wasm/plugin.go
scheduler/pkg/plugins/wasm/plugin_perf_test.go
scheduler/pkg/plugins/wasm/plugin_test.go
scheduler/pkg/plugins/wasm/runtime.go

/kind cleanup
This PR adds the copyright header, which we usually add even in the sub projects.
Fixes #
```release-note
NONE
```

add: add the copyright header

---

.gitignore
Makefile
internal/e2e/go.mod
internal/e2e/go.sum
internal/e2e/plugin_perf_test.go
internal/e2e/profiler/profiler.go
scheduler/cmd/scheduler/main.go
scheduler/go.mod
scheduler/go.sum
scheduler/plugin/plugin.go
scheduler/plugin/plugin_test.go
scheduler/testdata/testdata.go

/kind feature
This adds the profile make target, which uses wzprof to generate cpu and memory profiling data from the webassembly guest. This is a basic implementation to help people understand the costs of the current plugin. Ideas welcome to simplify the flow.
NONE
here's an example run:
```bash
$ make profile
Main binary filename not available.
Type: cpu
Time: Jun 3, 2023 at 12:43pm (+08)
Duration: 2.11ms, Total samples = 1802.46us (85.52%)
Showing nodes accounting for 1786.46us, 99.11% of 1802.46us total
Dropped 7 nodes (cum <= 9.01us)
flat  flat%   sum%        cum   cum%
652.78us 36.22% 36.22%   990.91us 54.98%  runtime.alloc
174.60us  9.69% 45.90%   174.60us  9.69%  (runtime.gcBlock).state
163.53us  9.07% 54.98%   163.53us  9.07%  (runtime.gcBlock).setState
107.92us  5.99% 60.96% …
```

Add profile make target

---

scheduler/go.mod
scheduler/go.sum
scheduler/plugin/export_test.go
scheduler/plugin/plugin.go
scheduler/plugin/plugin_test.go

/kind feature
This PR changes the host to always assign the same guest instance to the same Pod.
Two motivations here.
This change simplifies the problem how to support the cycle state. That's difficult because users can put any data into cycle state, and we don't know what'll be put.
After this PR, we don't need to pass the cycle state between host and guest; the guest initializes the cycle state inside of it and uses the same cycle state in the same scheduling.
Obviously, this idea means that users cannot pass the data from one plugin to other plugin through the cycle state, but that usecase is rare. (Actually, AFAIK, no in-tree plugins do that) 
Not saying we never support it in the future though, I'd say we don't need to prioritize it.
Thanks to the snapshot, the NodeInfo and Pod …

feature: always assign the same instance to the same Pod

---

guest/RATIONALE.md

/kind documentation
This reverse documents a decision we made about TinyGo.
NONE
documents the most important part of https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/pull/6
NONE
N/A

docs: adds RATIONALE.md with section on why TinyGo

---

internal/e2e/profiler/profiler.go
scheduler/cmd/scheduler/main.go
scheduler/plugin/export_test.go
scheduler/plugin/guest.go
scheduler/plugin/host.go
scheduler/plugin/plugin.go
scheduler/plugin/plugin_test.go
scheduler/plugin/pool.go
scheduler/plugin/pool_test.go
scheduler/test/testdata.go

/kind cleanup
This extracts the guest pool into its own type so that it can be unit tested without export helpers. Notably, this makes it a generic type which makes testing a lot easier. In the process, I found and fixed a test bug.
This also stubs all the host-side plugins in declaration order according to the framework interface. This helps me understand what we are implementing, and allows the IDE to find the upstream documentation vs guessing.
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/interface.go#L304-L506
NONE
NONE
N/A

extracts out pool and stubs plugin functions

---

.github/workflows/commit.yaml
.github/workflows/testdata.yaml
Makefile
examples/filter-simple/go.mod
examples/noop/go.mod
guest/filter.go
guest/go.mod
internal/e2e/plugin_perf_test.go
kubernetes/proto/api/generated.pb.go
kubernetes/proto/api/generated_vtproto.pb.go
kubernetes/proto/go.mod
kubernetes/proto/meta/generated.pb.go
kubernetes/proto/meta/generated_vtproto.pb.go
scheduler/test/testdata.go

/kind cleanup
This sets up basic CI with a couple notable targets:
* `make check`: runs various linters and formatters, and ensures projects build.
* `make test-scheduler`: runs scheduler-based unit and e2e tests.
None
Later, we can make tests that run in tinygo for the guest, but as that's tricky I left things here for now.
NONE
N/A

ci: adds basic setup

---

scheduler/plugin/plugin.go

/kind cleanup
The scheduling framework doesn't call Score() of the same plugin in parallel. So, we don't need to have `pl.pool.assignedToSchedulingPodLock.Lock()`, it's the lock to protect the guest from using at the same time.
ref:  https://github.com/kubernetes/kubernetes/blob/be14b026e33b682c52750741a2256373e480b7d7/pkg/scheduler/framework/runtime/framework.go#L1037
Fixes #
```release-note
NONE
```
```benchstat
(trivial)
```

fix(host): remove lock from Score

---

internal/e2e/plugin_perf_test.go
scheduler/plugin/export_test.go
scheduler/plugin/plugin.go
scheduler/plugin/plugin_test.go
scheduler/plugin/pool.go
scheduler/plugin/pool_test.go

/kind bug
Before, we used the UID to identify which cycle is in progress. However, when a scheduling cycle fails, the same UID can happen the next time.
This uses the pointer instead as this is different per run, and easier to compare in wasm. We use the lower bits as that's likely to not conflict, easier to use in wasm, and also can't identify fully the real host memory address.
Finally, this resets the pointer between benchmark runs. This makes sure a run isn't accidentally faster. Before, it was faster due to colliding on the same UID. By resetting the pointer, we avoid re-creating that issue.
NONE
I noticed curious results in the prior PR. The current results look a lot more realistic
NONE
```
goos: darwin
goarch: arm64
pkg: sigs.k8s.io/kube-scheduler-wasm-extension/internal/e2e …
```

Switches from UID to pointer for identifying cycle IDs

---

guest/internal/imports/mem.go
internal/e2e/go.mod
internal/e2e/go.sum
scheduler/go.mod
scheduler/go.sum

/kind cleanup
We're constantly tracking performance concerns and updating to the latest wazero release makes notable improvements without any change to the guest.
Performance related changes in the latest patch were thanks to @ncruces
NONE
```benchstat
goos: darwin
goarch: arm64
pkg: sigs.k8s.io/kube-scheduler-wasm-extension/internal/e2e
│  v1.2.0.txt  │            v1.2.1.txt             │
│    sec/op    │   sec/op     vs base              │
PluginFilter/noop-wat/params:_small-12           267.4n ±  2%   257.6n ± 4%  -3.65% (p=0.024 n=6)
PluginFilter/noop-wat/params:_real-12            270.4n ±  1%   270.1n ± 1%       ~ (p=0.623 n=6)
PluginFilter/noop/params:_small-12               333.2n ±  1%   329.2n ± 0%  -1.19% (p=0.002 n=6)
PluginFilter/noop/params:_real-12                337.0n ± …
```

Updates wazero to 1.2.1

---

scheduler/go.mod
scheduler/plugin/export_test.go
scheduler/plugin/plugin.go
scheduler/plugin/plugin_test.go
scheduler/plugin/pool.go
scheduler/plugin/pool_test.go

/kind cleanup
In #39 we switched from using the pod UID to the pointer due to a problem identifying of how to handle the same pod being rescheduled sequentially on error. @sanposhiho found that since `PreFilter` must always be called, we can reset state always on that hook. A later change can instruct the guest to always dump any cache on `PreFilter` even if the UID is the same as last time. Meanwhile, this change mechanically switches the host-side index back to the pod UID.
NONE
```benchstat
goos: darwin
goarch: arm64
pkg: sigs.k8s.io/kube-scheduler-wasm-extension/internal/e2e
│  before.txt  │             after.txt             │
│    sec/op    │   sec/op     vs base              │
PluginFilter/noop-wat/params:_small-12            266.8n ± 0%   263.2n ± 0%  -1.31% (p=0.002 n=6) …
```

Changes guest index back to UID

---

internal/e2e/go.mod
internal/e2e/guest_test.go
internal/e2e/plugin_perf_test.go
internal/e2e/profiler/profiler.go
scheduler/plugin/export_test.go
scheduler/plugin/plugin.go
scheduler/plugin/plugin_test.go
scheduler/plugin/runtime.go

/kind bug
Fix wzprof usage to enable profiling.
none
A couple things were missing:
* The method wzprof.Profiling.Prepare needs to be called on the compiled module before instantiation.
* The wazero runtime needs to have debug info and custom sections enabled.
As you can see the method to get access to the CompiledModule from the profiler main function is a bit hacky. Feel free to edit.
```release-note
NONE
```
N/A

Make profiler work

---

internal/e2e/go.mod
internal/e2e/go.sum
scheduler/go.mod
scheduler/go.sum

/kind cleanup
This updates to wazero 1.3.0, which is Go 1.21 ready.
Go 1.21 will be out in August, and this allows us to use release candidates prior without risk.
NONE
https://github.com/tetratelabs/wazero/releases/tag/v1.3.0
NONE
The performance has degraded since last change, but I don't recommend skipping this version. I'll start a thread offline in case someone has ideas.
```benchstat
goos: darwin
goarch: arm64
pkg: sigs.k8s.io/kube-scheduler-wasm-extension/internal/e2e
│  1.2.1.txt  │             1.3.0.txt             │
│   sec/op    │   sec/op     vs base              │
PluginPreFilter/noop-wat/params:_small-12                 132.4n ± 1%   132.1n ± 0%       ~ (p=0.784 n=6)
PluginPreFilter/noop-wat/params:_real-12                  133.2n ± 1%   132.3n ± 1%  -0.71% (p=0.048 n=6) …
```

deps: updates to wazero 1.3.0

---

Makefile
internal/e2e/go.mod
internal/e2e/guest/go.mod
internal/e2e/guest/go.sum
internal/e2e/guest/guest_test.go
internal/e2e/scheduler/scheduler_test.go

/kind cleanup
This changes the guest codec benchmarks to actually run in wasm. By using TinyGo with wazero, we can see performance of unmarshal realistically. Before, the benchmarks were run in normal go, even if they used the same library as the guest used.
When you run `make bench`, tinygo compiles the benchmarks to wasm, and then runs that wasm with wazero. So, the console output is coming from wasm functions compiled from Go benchmarks.
Our makefile ensures that the wazero version is the same as what the scheduler plugin uses (via go.mod). Since the wazero command configures the module to use real clocks, the performance report should be accurate.
NONE
This doesn't solve for real data yet because I can't get the yaml to proto converter to work in TinyGo. We may want to check in …

Run codec benchmarks in wasm

---

internal/e2e/profiler/profiler.go
internal/e2e/scheduler/scheduler_test.go
scheduler/go.mod
scheduler/plugin/config.go
scheduler/plugin/http.go
scheduler/plugin/http_test.go
scheduler/plugin/plugin.go
scheduler/plugin/plugin_test.go
scheduler/test/testdata.go

/kind feature
/kind api-change
Extends the current plugin config to use instead a URI. In the case of `file://` the behavior is the same as it is currently. In the case of `http(s)://` it will fetch the URI and try to evaluate it as a wasm payload.
This PR is based on earlier work on `dapr/component-contrib`. See: https://github.com/dapr/components-contrib/pull/3005
n/a will create if required.
n/a
```release-note
Changes `PluginConfig.ConfigPath` to `PluginConfig.ConfigURL`. A local path must now be prefixed with `file://`. A local path will be of the form `file://relativepath/myfile.wasm` or `file:///absolute/path/to/myfile.wasm`.
```
n/a

config: add support to file:// and http(s):// URIs

---

RATIONALE.md
internal/e2e/profiler/profiler.go
internal/e2e/scheduler/scheduler_test.go
internal/e2e/scheduler_perf/scheduler_perf_test.go
scheduler/cmd/scheduler/config.go
scheduler/cmd/scheduler/config_test.go
scheduler/cmd/scheduler/main.go
scheduler/go.mod
scheduler/go.sum
scheduler/plugin/plugin.go
scheduler/plugin/plugin_test.go

/kind feature
This PR changes the entry point to read the scheduler configuration before it initializes the scheduler (app.NewSchedulerCommand) and allows us to have multiple wasm plugins.
```yaml
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
- plugins:
multipoint:
enabled:
- name: wasmplugin1
- name: wasmplugin2
pluginConfig:
- name: wasmplugin1
args:
guestPath: "/path/to/wasm-plugin1"
- name: wasmplugin2
args:
guestPath: "/path/to/wasm-plugin2"
```
Fixes #23
```release-note
The scheduler can have multiple wasm plugins.
```
```benchstat
N/A (no benchmark related area in this change.)
```

allow the scheduler configuration to have multi wasm plugins

---

Makefile

/kind bug
Fix makefile bug
Fixes #84 
```release-note
NONE
```
```benchstat
```

fix Makefile bug

---

scheduler/plugin/export_test.go
scheduler/plugin/plugin.go
scheduler/plugin/plugin_test.go

/kind bug
We have to use guests in guestPool.binding during binding cycles.
Fixes #
```release-note
```
```benchstat
```

fix: use correct guest in binding cycles

---

scheduler/plugin/plugin_test.go

/kind bug
We can't pass specific integer to %v. We get the error below.
!v(PANIC=String method: runtime error: index out of range [2147483647] with length 6)
```release-note
NONE
```
```benchstat
```

Fix minor bug about %v

---

internal/e2e/go.mod
internal/e2e/go.sum
scheduler/go.mod
scheduler/go.sum

Hi, this is Edoardo from the wazero team. I am opening this PR to upgrade to the latest version and will stick around to help with reviewing some PRs! If you need some help especially with Wasm feel free to ping me here or on the k8s/Gophers Slack!
This upgrades to wazero [v1.6.0]. This release notably introduces a new
experimental optimizing compiler backend for arm64.
As compared to v1.3.0, cumulatively this upgrade brings several
stability enhancements; including compiler bugs, improvements to WASI
support, especially when paired with the newer Go `GOOS=wasip1` backend,
and fixes to a potential memory leak.
Read more on the previous release notes ([v1.3.1][v1.3.1],
[v1.4.0][v1.4.0], [v1.5.0][v1.5.0])
[v1.3.1]: https://github.com/tetratelabs/wazero/releases/tag/v1.3.1
[v1.4.0]: …

chore: wazero v1.6.0 version bump

---

internal/e2e/go.mod
internal/e2e/go.sum
scheduler/go.mod
scheduler/go.sum

This will update [wazero](https://wazero.io/) to v1.7.0. The v1.7.0. release marks a milestone in the wazero project, replacing our old compiler architecture with a [new optimizing compiler backend.][docs]. It also introduces experimental support to the thread spec.
We will officially announce the final v1.7.0 release in just a few days, during [Wasm I/O](https://wasmio.tech/), after which we will undraft this PR and update it to the latest tag.
~Let me know if you'd rather merge this PR before the official release. This draft PR is intended to let your CI checks run and verify everything is in order before our final release.~
[docs]: https://wazero.io/docs/how_the_optimizing_compiler_works/
/kind feature
```release-note
NONE
```
the optimizing compiler brings >40% run-time improvement at …

deps: updates wazero to v1.7.0

---

internal/e2e/profiler/profiler.go

/kind bug
`experimental.FunctionListenerFactoryKey` is [deprecated](https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/actions/runs/9057576330/job/24881809518) and `make check` is failing on `main` branch.
Fixes #
```release-note
NONE
```
```benchstat
```

Replace deprecated `experimental.FunctionListenerFactoryKey` with `experimental.WithFunctionListenerFactory` 

---

internal/e2e/scheduler_perf/scheduler_perf_test.go

/kind cleanup
This PR simply changes how we run the `scheduler-perf` benchmarks by only starting the extender plugin when it's referenced in the configuration.
```release-note
NONE
```
```benchstat
N/A
```

Only start the extender plugin when needed in scheduler-perf

---

.github/workflows/commit.yaml
.github/workflows/testdata.yaml
Makefile
scheduler/test/util.go

The previous version of `golangci-lint` (1.53.2) crashed under recent versions of Go.
/kind cleanup
The `lint` make target currently fails with recent versions of Go (e.g. 1.23.3) because the version of `golangci-lint` that we use crashes at runtime.
Updating to 1.61.0 solves this.
I also had to update the version of Go used in the CI workflows to get them to pass.
I thus updated to the latest version, and did the same for TinyGo.
The latest TinyGo now has multiple `wasi` targets, and the main one inherits from `wasip1`. I had to change the way we generate the test target to deal with this inheritance.
```release-note
NONE
```
```benchstat
N/A
```

Upgrade `golangci-lint` to 1.61.0

---

examples/nodenumber/main.go
examples/nodenumber/main_test.go
internal/e2e/scheduler_perf/wasm/nodenumber/main.go

/kind bug
The nodeNumber plugin is intended to scores higher if the node name and pod name suffixes match.
But in implementation, it uses Pod's .`Spec.nodeName` not a `.metadata.Name`.
So PreScore allways return nothing, and therefore allways `match=true` in Score.
This PR fix this problem
Fixes #
```release-note
change nodeNumber plugin to follow specification.
```
[after.txt](https://github.com/user-attachments/files/17759131/after.txt)
[before.txt](https://github.com/user-attachments/files/17759122/before.txt)
```benchstat
❯ benchstat before.txt after.txt
goos: darwin
goarch: arm64
pkg: sigs.k8s.io/kube-scheduler-wasm-extension/internal/e2e/scheduler
cpu: Apple M1
│  before.txt  │              after.txt              │
│    sec/op    │    sec/op     vs base               │ …
```

fix nodenumber plugin to use Pod name instead of pod.spec.nodeName

---

docs/tutorial.md

/kind cleanup
Fixed the indentation of `pluginConfig` so that it aligns correctly under `profiles`.
Fixes #
```release-note
NONE
```
```benchstat
```

chore(tutorial): fix YAML indentation in scheduler plugin example

---

scheduler/cmd/scheduler/config.go

/kind bug
By default, Go’s `flag` package rejects any flags it doesn’t know, so our scheduler wrapper was swallowing all kube-scheduler parameters except `--config`. This PR switches to `spf13/pflag` and enables unknown-flag passthrough, so flags like `--v`, `--secure-port`, and any future additions are correctly forwarded to the real scheduler.
Fixes #
```release-note
NONE
```
```benchstat
```

fix: allow kube-scheduler to pass through flags other than --config
